/* Quijo V1.2 screens. Private data stays in the existing encrypted payload. */
(function(global){
'use strict';
global.QFInsightsUI=function(ctx){
 const A=global.QFInsights,M=global.QFModel;
 const {esc,fmt,money,percent,dateLabel,monthLabel,heading,icon,openSheet,closeSheet,toast}=ctx;
 let fromChoice=null,toChoice=null,benchmarkChoice=null,benchmarkMode='index',pendingBenchmark=null;
 const g=()=>ctx.get(),state=()=>A.state(g().payload);
 const btn=(act,label,ico='',extra='')=>'<button type="button" class="btn '+extra+'" data-xact="'+act+'">'+(ico?icon(ico):'')+label+'</button>';
 const go=(view,label)=>'<button type="button" class="btn quiet" data-view="'+view+'">'+label+' '+icon('arrow')+'</button>';
 const badge=(text,cls='')=>'<span class="badge '+cls+'">'+text+'</span>';
 const pp=v=>(v>0?'+':'')+fmt(v,2)+' pp';
 const bar=(v,cls='')=>'<div class="progress '+cls+'"><span style="width:'+Math.max(0,Math.min(100,v||0))+'%"></span></div>';
 const sign=v=>v<0?'negative':'positive';
 const empty=(title,text,action='')=>'<section class="card feature-empty"><div class="feature-empty-icon">'+icon('trend')+'</div><h2>'+title+'</h2><p class="small muted">'+text+'</p>'+action+'</section>';
 function checkShow(){if(g().hide){toast('Muestra los importes con el ojo para editar datos privados.');return false;}return true;}
 async function saveExtra(mutator){const next=structuredClone(g().payload);next.insights=A.sanitize(next.insights);mutator(next);await ctx.persistNext(next);}
 function choices(){const dates=Object.keys(g().payload.snapshots).sort();const to=dates.includes(toChoice)?toChoice:g().data.date;const befores=dates.filter(d=>d<to);const from=befores.includes(fromChoice)?fromChoice:befores.at(-1);return {dates,to,from};}
 function previousDiff(){const {payload,data}=g(),from=A.previous(payload,data.date);return from?A.diff(payload,from,data.date):null;}
 function homeExtra(){const {data}=g(),d=previousDiff(),goals=state().goals;return '<div class="feature-launch-grid">'+
 '<section class="card feature-launch"><p class="label">01 / MES A MES</p><h2>'+ (d?'El cambio, con contexto.':'Tu siguiente cierre cuenta.')+'</h2><p class="small muted">'+(d?percent(d.totals.financial.pct,2,true)+' en patrimonio financiero frente a '+dateLabel(d.from)+'. Incluye flujos.':'El historial del Excel sigue visible. Para comparar posiciones necesitamos dos fotos importadas.')+'</p>'+go('cambios','Ver cambios')+'</section>'+
 '<section class="card feature-launch"><p class="label">02 / OBJETIVOS</p><h2>'+ (goals.length?goals.length+' metas en perspectiva.':'Ponle destino al ahorro.')+'</h2><p class="small muted">Reservas, objetivos personales y progreso. Sin sumar dos veces el mismo dinero.</p>'+go('objetivos','Ver objetivos')+'</section>'+
 '<section class="card feature-launch"><p class="label">03 / BENCHMARK</p><h2>Compara lo comparable.</h2><p class="small muted">Mismos meses y euros. Flujos conciliados y datos de referencia con fuente.</p>'+go('benchmark','Abrir comparador')+'</section></div>';}
 function portfolioExtra(){const d=previousDiff();if(!d)return '<div class="note">El cambio de pesos se activar&aacute; cuando importes otra foto. No reconstruimos posiciones antiguas a partir del total del Excel.</div>';
 return '<section class="card"><div class="row between wrap"><div><p class="label">CAMBIO DE PESOS</p><h2>Frente al '+dateLabel(d.from)+'</h2></div>'+go('cambios','Todos los cambios')+'</div><div class="weight-chips">'+d.blocks.map(b=>'<div><span>'+esc(b.name)+'</span><strong>'+pp(b.delta)+'</strong></div>').join('')+'</div><p class="tiny muted">Puntos porcentuales, no rentabilidad. Incluye reasignaciones y mercado.</p></section>';}
 function savingExtra(year,ordinary){const {data}=g(),s=M.savings(data,year,ordinary);if(!s.count)return '';const ranked=[...s.months].sort((a,b)=>b.net-a.net),best=ranked[0],worst=ranked.at(-1);return '<section class="card"><div class="row between wrap"><h2>Perspectiva del a&ntilde;o</h2>'+badge(ordinary?'Ordinario':'Total')+'</div><div class="metric-grid" style="margin-top:16px"><div><span class="label">Media / mes</span><b>'+money(s.net/s.count)+'</b><span class="tiny muted">Sobre '+s.count+' meses</span></div><div><span class="label">Mayor ahorro</span><b>'+esc(monthLabel(best.period))+'</b><span class="small">'+(g().hide?percent(best.rate,1):money(best.net))+'</span></div><div><span class="label">Menor ahorro</span><b>'+esc(monthLabel(worst.period))+'</b><span class="small">'+(g().hide?percent(worst.rate,1):money(worst.net))+'</span></div></div><p class="tiny muted" style="margin-top:12px">Mejor y peor seg&uacute;n excedente del mes; no proyectamos meses futuros.</p></section>';}
 function stockExtra(p){const total=M.stockTotals(g().data),contrib=total.cost?(p.value-p.cost+(p.dividends||0))/total.cost*100:null;const d=previousDiff(),r=d?.positions.find(x=>x.id===p.id);return '<div class="soft"><p class="label">PESO Y RESULTADO</p><div class="tooltip-row"><span>Peso dentro de acciones</span><b>'+percent(M.pct(p.value,total.value))+'</b></div><div class="tooltip-row"><span>Aporte al resultado / coste del bloque</span><b>'+ (contrib===null?'--':pp(contrib))+'</b></div>'+(r?'<div class="tooltip-row"><span>Cambio de peso sobre cartera</span><b>'+pp(r.weightDelta)+'</b></div>':'')+'<p class="tiny muted">Contribuci&oacute;n simple de la posici&oacute;n abierta y sus dividendos al coste conjunto actual. No es atribuci&oacute;n hist&oacute;rica ni alfa.</p></div>';}
 function changesView(){const {payload,data}=g(),c=choices(),d=c.from?A.diff(payload,c.from,c.to):null;let html=heading('Qu&eacute; cambi&oacute; este mes.','Dos fotos, sus diferencias y lo que todav&iacute;a no podemos atribuir.');
 if(!d){const series=M.historical(data,'financial'),last=series.at(-1),prev=series.at(-2);return html+empty('Falta una segunda foto de posiciones.','Importa el siguiente cierre sin borrar septiembre. Se conservar&aacute;n ambos y aparecer&aacute;n cambios de pesos y posiciones.',go('datos','Importar y revisar cierres'))+(prev?'<section class="card" style="margin-top:16px"><h2>Lo que ya dice tu Excel</h2><p class="small muted">'+esc(prev.period)+' &rarr; '+esc(last.period)+' &middot; observaciones hist&oacute;ricas, no dos carteras detalladas.</p><div class="kpi-value">'+percent((last.value/prev.value-1)*100,2,true)+'</div><p class="note">Variaci&oacute;n del patrimonio financiero. Incluye dinero que entra o sale; no es rendimiento.</p></section>':'');}
 const rec=A.portfolioMonths(payload).find(r=>r.from===d.from&&r.to===d.to&&r.eligible);
 html+='<div class="stack"><section class="card comparison-selector"><label class="field">Desde<select id="changes-from">'+c.dates.filter(v=>v<c.to).map(v=>'<option value="'+v+'" '+(v===c.from?'selected':'')+'>'+dateLabel(v)+'</option>').join('')+'</select></label><span>'+icon('arrow')+'</span><label class="field">Hasta<select id="changes-to">'+c.dates.slice(1).map(v=>'<option value="'+v+'" '+(v===c.to?'selected':'')+'>'+dateLabel(v)+'</option>').join('')+'</select></label></section><div class="grid3">'+[['financial','Patrimonio financiero'],['invested','Invertido'],['available','Caja disponible']].map(([key,name])=>'<div class="card"><p class="label">'+name+'</p><div class="kpi-value">'+money(d.totals[key].now)+'</div><div class="small '+sign(d.totals[key].delta)+'">'+percent(d.totals[key].pct,2,true)+' <span class="muted">vs anterior</span></div></div>').join('')+'</div>';
 html+='<section class="card"><div class="row between wrap"><h2>De un saldo al siguiente</h2>'+badge('Solo bloque invertido')+'</div><div class="reconcile-steps">'+[['Inicio',d.old.invested],['Flujo externo neto',rec?rec.net:null],['Resultado residual',rec?rec.residual:null],['Cierre',d.now.invested]].map(([n,v],i)=>'<div><span class="label">'+n+'</span><strong>'+ (v===null?'Pendiente':money(v))+'</strong><span class="tiny muted">'+['Fondos, PP, acciones, ETP','No incluye traspasos internos','No atribuye por activo','Sin efectivo bancario'][i]+'</span></div>').join('')+'</div><p class="note">'+(rec?'El resultado residual es cierre &minus; inicio &minus; flujos confirmados. Puede incluir comisiones, dividendos y cambios de valor; no permite atribuir todo a mercado ni a un gestor.':'Sin conciliar entradas y salidas no llamamos a la diferencia &ldquo;ganancia de mercado&rdquo;. Puedes registrarlas en el comparador.')+'</p>'+go('benchmark','Conciliar flujos')+'</section>';
 html+='<section class="card"><h2>Cambios de asignaci&oacute;n</h2><div class="table-scroll"><table class="summary-table"><thead><tr><th>Bloque</th><th>Antes</th><th>Ahora</th><th>Cambio</th></tr></thead><tbody>'+d.blocks.map(b=>'<tr><td>'+esc(b.name)+'</td><td>'+percent(b.before)+'</td><td>'+percent(b.after)+'</td><td>'+pp(b.delta)+'</td></tr>').join('')+'</tbody></table></div></section>';
 html+='<section class="card"><div class="row between wrap"><h2>Las posiciones, una a una</h2>'+badge(d.positions.filter(p=>p.status==='Nueva en el cierre').length+' nuevas &middot; '+d.positions.filter(p=>p.status==='Ya no figura').length+' ausentes')+'</div><div class="table-scroll"><table class="summary-table"><thead><tr><th>Producto</th><th>Variaci&oacute;n valor</th><th>Cambio peso total</th></tr></thead><tbody>'+d.positions.map(p=>'<tr><td>'+esc(p.name)+'<span class="table-meta">'+p.status+'</span></td><td>'+money(p.delta,2)+'</td><td>'+pp(p.weightDelta)+'</td></tr>').join('')+'</tbody></table></div><p class="note">Un saldo mayor no demuestra una compra ni un mejor rendimiento. &ldquo;Nueva&rdquo; y &ldquo;ausente&rdquo; describen las fotos; cambios de identificador o de nombre tambi&eacute;n pueden influir.</p></section></div>';return html;
 }
 function reservePanel(){const {payload,data}=g(),t=M.totals(data),targets=payload.settings.goals||{},values=[t.available,M.sum(data.positions.filter(p=>p.group==='axa').map(p=>p.value)),M.sum(data.positions.filter(p=>p.group==='gamma').map(p=>p.value))];return '<section class="card"><div class="row between wrap"><div><p class="label">TU BASE DE SEGURIDAD</p><h2>Reservas por funci&oacute;n</h2></div>'+go('plan','Editar reservas')+'</div><div class="reserve-grid">'+[['account','Cuenta disponible'],['moneyMarket','Monetario AXA'],['defensivePlus','Defensivo+ Gamma']].map(([k,n],i)=>{const target=targets[k],pr=target?values[i]/target*100:null;return '<div class="soft"><span class="label">'+n+'</span><strong class="reserve-value">'+(pr===null?'Sin meta':percent(pr,0))+'</strong>'+bar(pr)+'<p class="small muted">'+money(values[i])+(target?' / '+money(target):' disponibles')+'</p></div>';}).join('')+'</div><p class="note">Gamma no cuenta como liquidez para emergencias. AXA y cuenta no se suman al crear una meta: son saldos ya incluidos en tu patrimonio.</p></section>';}
 function goalsView(){const {data}=g(),goals=state().goals;return heading('Tus objetivos, a la vista.','Cada meta tiene un saldo, una fecha y un criterio. No son inversiones nuevas.',btn('goal-new','Crear objetivo','target','primary'))+'<div class="stack">'+reservePanel()+(goals.length?'<div class="goals-grid">'+goals.map(goal=>{const s=A.goalStatus(goal,data);const status=s.left===0?'Objetivo alcanzado':goal.due&&s.months===0?'Revisa el plazo':'En construcci&oacute;n';return '<section class="card goal-card"><div class="row between"><span class="goal-icon">'+icon('target')+'</span>'+badge(status)+'</div><h2>'+esc(goal.title)+'</h2><div class="goal-percent">'+percent(s.progress,1)+'</div>'+bar(s.progress)+'<div class="row between small" style="margin-top:12px"><span>'+money(s.current)+'</span><span class="muted">de '+money(goal.target)+'</span></div><div class="goal-divider"></div><div class="tooltip-row"><span>Falta</span><b>'+money(s.left)+'</b></div><div class="tooltip-row"><span>Fecha objetivo</span><b>'+ (goal.due?dateLabel(goal.due):'Sin fecha')+'</b></div><div class="tooltip-row"><span>Necesario / mes</span><b>'+(s.left===0?money(0):s.neededMonthly===null?'--':money(s.neededMonthly))+'</b></div><p class="tiny muted">'+(goal.monthly>0?'A tu ritmo configurado: '+s.projectedMonths+' meses, sin suponer rentabilidad.':'Define un ritmo mensual para estimar el plazo.')+'</p><p class="tiny muted">Base: '+basisName(goal.basis)+'</p><div class="button-row" style="margin-top:14px"><button type="button" class="btn wide" data-xact="goal-edit" data-id="'+esc(goal.id)+'">Editar meta</button></div></section>';}).join('')+'</div>':empty('La pr&oacute;xima meta empieza aqu&iacute;.','Puedes vincularla al patrimonio, la caja, el fondo del hijo, las pensiones, el ahorro anual o llevarla manualmente.',btn('goal-new','Crear mi primera meta','target','primary')))+'<section class="card"><h3>Metas, no cuentas adicionales</h3><p class="small muted" style="margin-top:8px">Varias metas pueden observar el mismo dinero. No se suman entre s&iacute;, no reservan dinero en el banco y no aumentan tu patrimonio. Las fechas se calculan desde la fecha de tu foto, no desde una cotizaci&oacute;n en directo.</p>'+go('fire','Ver escenario FIRE')+'</section></div>';}
 function basisName(k){return {financial:'Patrimonio financiero',cash:'Cuenta disponible',reserve:'Cuenta + AXA (sin Gamma)',child:'Posiciones reservadas para el hijo',pension:'Planes de pensiones',savings:'Ahorro total del a&ntilde;o de la foto',manual:'Importe manual, solo seguimiento'}[k];}
 function goalDialog(id){if(!checkShow())return;const goal=state().goals.find(x=>x.id===id)||{id:'',title:'',target:'',basis:'manual',current:0,monthly:0,due:''};openSheet(goal.id?'Editar objetivo':'Nuevo objetivo','<form id="goal-form" class="stack-sm" data-goal-id="'+esc(goal.id)+'"><label class="field">Nombre<input id="g-title" maxlength="80" required value="'+esc(goal.title)+'" placeholder="Tu meta"></label><div class="form-grid"><label class="field">Objetivo (&euro;)<input id="g-target" type="number" min="0.01" max="100000000000" step="0.01" required value="'+goal.target+'"></label><label class="field">Fecha objetivo (opcional)<input id="g-due" type="date" value="'+(goal.due||'')+'"></label></div><label class="field">Calcular el progreso desde<select id="g-basis">'+['manual','financial','cash','reserve','child','pension','savings'].map(k=>'<option value="'+k+'" '+(goal.basis===k?'selected':'')+'>'+basisName(k)+'</option>').join('')+'</select></label><div class="form-grid"><label class="field">Saldo manual (&euro;)<input id="g-current" type="number" min="0" max="100000000000" step="0.01" value="'+goal.current+'"><span class="tiny">Solo se usa con base manual.</span></label><label class="field">Ritmo previsto / mes (&euro;)<input id="g-monthly" type="number" min="0" max="1000000000" step="0.01" value="'+goal.monthly+'"></label></div><p class="note">La meta no crea dinero ni ejecuta aportaciones. Sin hip&oacute;tesis de rentabilidad. Mantiene el mismo cifrado que tus cierres.</p>'+btn('goal-save','Guardar objetivo','check','primary wide')+(goal.id?'<button type="button" class="btn danger wide" data-xact="goal-delete" data-id="'+esc(goal.id)+'">Eliminar este objetivo</button>':'')+'</form>');}
 function selectedBenchmark(){const bs=state().benchmarks;return bs.find(b=>b.id===benchmarkChoice)||bs[0]||null;}
 function comparisonChart(c){const vals=[{period:c.from.slice(0,7),portfolioIndex:100,benchmarkIndex:100},...c.rows],W=640,H=280,L=48,R=20,T=20,B=38;const min=Math.min(...vals.flatMap(r=>[r.portfolioIndex,r.benchmarkIndex]))-2,max=Math.max(...vals.flatMap(r=>[r.portfolioIndex,r.benchmarkIndex]))+2;const x=i=>L+i/Math.max(1,vals.length-1)*(W-L-R),y=v=>T+(max-v)/(max-min)*(H-T-B);let h='<svg class="chart" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="Evolucion base 100 de cartera y referencia">';for(let i=0;i<4;i++){const v=min+(max-min)*i/3;h+='<line class="gridline" x1="'+L+'" y1="'+y(v)+'" x2="'+(W-R)+'" y2="'+y(v)+'"/><text x="'+(L-8)+'" y="'+(y(v)+4)+'" text-anchor="end">'+fmt(v,0)+'</text>';}
 for(const [field,color] of [['portfolioIndex','var(--brand)'],['benchmarkIndex','var(--benchmark)']])h+='<path d="'+vals.map((p,i)=>(i?'L':'M')+x(i)+' '+y(p[field])).join(' ')+'" fill="none" stroke="'+color+'" stroke-width="3" stroke-linejoin="round"/>';
 vals.forEach((r,i)=>{if(i===0||i===vals.length-1||i%Math.ceil(vals.length/5)===0)h+='<text x="'+x(i)+'" y="'+(H-10)+'" text-anchor="middle">'+esc(r.period)+'</text>';h+='<circle cx="'+x(i)+'" cy="'+y(r.portfolioIndex)+'" r="4" fill="var(--brand)"/>';});return h+'</svg><div class="compare-legend"><span><i style="background:var(--brand)"></i>Tu cartera invertida</span><span><i style="background:var(--benchmark)"></i>Referencia '+(c.mode==='mix'?'75/25':'')+'</span></div>';}
 function metric(v,k){if(v===null||!Number.isFinite(v))return '--';return k==='sharpe'?fmt(v,2):percent(v,2,k==='cumulative'||k==='annualized');}
 function benchmarkView(){const {payload,data}=g(),p=A.portfolioMonths(payload).filter(r=>r.to<=data.date),bench=selectedBenchmark(),c=bench?A.compare(payload,bench,benchmarkMode,data.date):null,valid=p.filter(r=>r.eligible).length;let h=heading('Tu cartera, con referencia.','Un comparador funcional. Ning&uacute;n dato de mercado se inventa ni se descarga al abrir.',btn('benchmark-import','Importar referencia','upload','primary'));
 h+='<div class="stack"><div class="benchmark-readiness"><div>'+icon('database')+'<span><b>'+Object.keys(payload.snapshots).filter(d=>d<=data.date).length+'</b> fotos guardadas</span></div><div>'+icon('check')+'<span><b>'+valid+'</b> meses conciliados</span></div><div>'+icon('trend')+'<span><b>'+ (bench?bench.rows.length:0)+'</b> meses de referencia</span></div></div>';
 h+='<section class="card"><div class="row between wrap"><div><p class="label">01 / CALIDAD ANTES QUE METRICAS</p><h2>Cierres y flujos</h2></div>'+btn('close-confirm','Confirmar cierres','check')+'</div><p class="note" style="margin-top:12px">El comparador mide el bloque invertido (fondos, PP, acciones y ETP), sin efectivo bancario. Cuenta &rarr; fondo es entrada; DNCA &rarr; Vanguard es traspaso interno y no se registra como dinero nuevo.</p>'+(p.length?'<div class="month-ledger">'+p.slice(-18).reverse().map(r=>'<div class="ledger-row"><div><b>'+esc(monthLabel(r.period,true))+'</b><span class="table-meta">'+esc(r.reason)+'</span></div>'+ (r.eligible?'<strong class="'+sign(r.returnPct)+'">'+percent(r.returnPct,2,true)+'</strong>':'<span class="badge">Pendiente</span>')+'<button class="btn quiet" type="button" data-xact="flow-edit" data-id="'+r.to+'">Revisar</button></div>').join('')+'</div>':'<p class="empty-text">Con el siguiente cierre podremos conciliar el primer intervalo mensual. Los totales hist&oacute;ricos del Excel no sustituyen las fotos de posiciones.</p>')+'</section>';
 h+='<section class="card"><div class="row between wrap"><div><p class="label">02 / MISMO PERIODO, MISMA DIVISA</p><h2>Comparaci&oacute;n</h2></div>'+badge('EUR &middot; base 100')+'</div>';
 if(!bench){h+='<p class="empty-text">A&ntilde;ade una serie de rentabilidades mensuales en EUR, con dividendos o cupones reinvertidos. Por ejemplo, el MSCI ACWI o un ETF de acumulaci&oacute;n que lo siga. No se incluye un hist&oacute;rico precargado no verificado.</p>'+btn('benchmark-import','Cargar CSV o pegar tabla','upload','wide');}
 else {h+='<div class="benchmark-controls"><label class="field">Serie<select id="benchmark-select">'+state().benchmarks.map(b=>'<option value="'+esc(b.id)+'" '+(bench.id===b.id?'selected':'')+'>'+esc(b.name)+'</option>').join('')+'</select></label><div class="segmented"><button type="button" data-xact="bm-mode-index" class="'+(benchmarkMode==='index'?'active':'')+'">100% referencia</button><button type="button" data-xact="bm-mode-mix" class="'+(benchmarkMode==='mix'?'active':'')+'">75/25</button></div></div><p class="provenance">Fuente declarada: '+esc(bench.source)+'</p>';
 if(benchmarkMode==='mix')h+='<p class="note">75% referencia + 25% serie defensiva importada, rebalanceo mensual te&oacute;rico sin costes de operativa. No se presume que sea igual de arriesgada que tu cartera.</p>';
 if(!c?.rows.length){h+='<div class="comparison-empty"><h3>A&uacute;n no hay meses comparables</h3><p class="small muted">Necesitamos meses completos compartidos por los cierres conciliados y la referencia'+(benchmarkMode==='mix'?', incluyendo la columna defensivo_pct':'')+'. No rellenamos huecos.</p></div>';}
 else {h+='<div class="row between wrap" style="margin-top:20px">'+badge(dateLabel(c.from)+' &rarr; '+dateLabel(c.to))+badge(c.rows.length+' meses consecutivos')+'</div><div style="margin-top:12px">'+comparisonChart(c)+'</div><div class="table-scroll"><table class="summary-table"><thead><tr><th>M&eacute;trica</th><th>Cartera</th><th>Referencia</th></tr></thead><tbody>'+[['Acumulada','cumulative'],['Anualizada','annualized'],['Volatilidad anualizada','volatility'],['Sharpe','sharpe'],['Ca&iacute;da m&aacute;xima entre cierres','drawdown'],['Mejor mes','best'],['Peor mes','worst']].map(([n,key])=>'<tr><td>'+n+'</td><td>'+metric(c.portfolio[key],key)+'</td><td>'+metric(c.benchmark[key],key)+'</td></tr>').join('')+'</tbody></table></div><div class="row between small" style="margin-top:12px"><span>Diferencia acumulada (no alfa)</span><b>'+pp(c.portfolio.cumulative-c.benchmark.cumulative)+'</b></div><p class="note">'+(c.rows.length<12?'Con menos de 12 meses no mostramos anualizaci&oacute;n, volatilidad anualizada ni Sharpe. ':'12 meses son un m&iacute;nimo de visualizaci&oacute;n, no evidencia suficiente de habilidad. ')+(c.hasRiskFree?'Sharpe con rentabilidades mensuales excedentes sobre la serie libre de riesgo aportada. ':'Sin serie libre de riesgo, Sharpe permanece vac&iacute;o. ')+'Las ca&iacute;das entre cierres no capturan p&eacute;rdidas intramensuales. '+(c.skipped?'Se muestra el &uacute;ltimo tramo continuo; no se encadenan meses separados por huecos.':'')+'</p>'+(c.rows.some(r=>r.largeFlow)?'<p class="note warn">Hay entradas o salidas grandes: Modified Dietz puede desviarse de la TWR exacta, especialmente con mercados vol&aacute;tiles.</p>':'')+btn('benchmark-export','Exportar comparativa %','download')+'<details class="collapsible"><summary>Ver rentabilidades mensuales</summary><div class="table-scroll"><table class="summary-table"><thead><tr><th>Mes</th><th>Cartera</th><th>Referencia</th></tr></thead><tbody>'+c.rows.map(r=>'<tr><td>'+r.period+'</td><td>'+percent(r.returnPct,2,true)+'</td><td>'+percent(r.benchmarkPct,2,true)+'</td></tr>').join('')+'</tbody></table></div></details>';}
 h+='<div class="button-row" style="margin-top:20px">'+btn('benchmark-import','A&ntilde;adir serie','upload')+btn('benchmark-delete','Eliminar esta referencia','close','danger')+'</div>';}
 h+='</section><section class="card"><h3>Lo que estamos calculando</h3><p class="small muted" style="line-height:1.8;margin-top:10px">Modified Dietz: (cierre &minus; inicio &minus; flujos) / (inicio + flujos ponderados por los d&iacute;as restantes). Se asume flujo al final del d&iacute;a. Se encadenan los meses conciliados. Es una estimaci&oacute;n, no TWR exacta ni una auditor&iacute;a GIPS. No se descuentan dos veces los gastos ya reflejados en los saldos.</p><p class="tiny muted" style="margin-top:10px">Sharpe = media del exceso mensual / desviaci&oacute;n muestral del exceso mensual &times; &radic;12. Volatilidad = desviaci&oacute;n muestral de rentabilidades mensuales &times; &radic;12. La fuente de cada serie queda guardada con la referencia.</p></section></div>';return h;
 }
 function closeDialog(){const {payload,data}=g(),s=state(),dates=Object.keys(payload.snapshots).filter(d=>d<=data.date).sort();openSheet('Confirmar fechas de cierre','<div class="stack-sm"><p class="note warn">Marca solo fotos que realmente correspondan al final de mes. No cambies una foto de mitad de mes solo por hacerla comparable.</p>'+dates.map(d=>'<label class="checkline"><input type="checkbox" data-close-date="'+d+'" '+(s.closes[d]===A.stamp(payload.snapshots[d])?'checked':'')+' '+(!A.isEnd(d)?'disabled':'')+'> '+dateLabel(d)+(A.isEnd(d)?' &middot; posiciones de cierre':' &middot; no es fin de mes')+'</label>').join('')+btn('close-save','Guardar confirmaciones','check','primary wide')+'</div>');}
 function flowDialog(date){if(!checkShow())return;const {payload}=g(),r=A.portfolioMonths(payload).find(x=>x.to===date);if(!r)return;if(!A.isEnd(r.from)||!A.isEnd(r.to)||A.serial(r.to)-A.serial(r.from)!==1){toast('Este intervalo no une dos fines de mes consecutivos.');return;}const s=state(),record=s.flows[date];openSheet('Flujos de '+esc(monthLabel(r.period,true)),'<form id="flow-form" data-date="'+date+'" class="stack-sm"><div class="metric-grid"><div><span class="label">Inicio</span><b>'+money(r.start,2)+'</b></div><div><span class="label">Cierre</span><b>'+money(r.end,2)+'</b></div><div><span class="label">Intervalo</span><b>'+Math.round((Date.parse(r.to)-Date.parse(r.from))/86400000)+' d&iacute;as</b></div></div><p class="note">Solo flujos externos al bloque invertido. Entrada: positiva; retirada: negativa. Un dividendo cobrado fuera del bloque se anota como retirada para conservar su contribuci&oacute;n al resultado. No registres DNCA &rarr; Vanguard ni una compra financiada con dinero ya dentro del bloque.</p><label class="field">Una operaci&oacute;n por l&iacute;nea: AAAA-MM-DD;importe<textarea id="flow-items" rows="6" spellcheck="false" placeholder="Escribe fechas e importes reales. Sin operaciones externas: deja vacio.">'+esc(record?.items.map(f=>f.date+';'+f.amount).join('\n')||'')+'</textarea></label><label class="checkline"><input id="flow-confirm" type="checkbox" required> He incluido todas las entradas y salidas. Vac&iacute;o significa cero flujos, no datos desconocidos.</label><p class="tiny muted">Las fechas de ambos cierres tambi&eacute;n deben estar confirmadas. Reimportar saldos distintos invalida esta conciliaci&oacute;n.</p>'+btn('flow-save','Guardar flujos conciliados','check','primary wide')+'</form>');}
 function benchmarkDialog(){pendingBenchmark=null;openSheet('Importar referencia mensual','<form id="benchmark-form" class="stack-sm"><label class="field">Nombre de la referencia<input id="bm-name" required maxlength="100" placeholder="MSCI ACWI EUR neto / ETF elegido"></label><label class="field">Fuente y fecha de extracci&oacute;n<input id="bm-source" required maxlength="600" placeholder="Proveedor, URL y fecha real de consulta"></label><div class="form-grid"><label class="field">Fuente libre de riesgo (opcional)<input id="bm-rf-source" maxlength="600" placeholder="Necesaria si incluyes la serie"></label><label class="field">Fuente defensivo (opcional)<input id="bm-def-source" maxlength="600" placeholder="Necesaria para comparar 75/25"></label></div><label class="field">CSV de rentabilidades mensuales<input id="benchmark-file" type="file" accept=".csv,.txt,text/csv"></label><label class="field">O pega la tabla<textarea id="bm-text" rows="7" spellcheck="false" placeholder="mes;rentabilidad_pct;libre_riesgo_pct;defensivo_pct"></textarea></label><p class="note">Valores en porcentaje: 1,25 significa +1,25%, no 0,0125. Mes: AAAA-MM. Las columnas auxiliares pueden quedar vac&iacute;as. Cada fila debe ser un mes completo; no utilices YTD ni precios.</p><label class="checkline"><input id="bm-confirm" type="checkbox" required> Confirmo que la serie est&aacute; en EUR, son meses completos y la rentabilidad incluye dividendos/cupones reinvertidos. No es una serie price return.</label><div class="button-row">'+btn('benchmark-template','Plantilla CSV','download')+btn('benchmark-preview','Revisar antes de guardar','check','primary')+'</div></form>');}
 async function handle(act,el){const {payload,data}=g();switch(act){
 case 'goal-new':goalDialog();break;
 case 'goal-edit':goalDialog(el.dataset.id);break;
 case 'goal-save':{if(!checkShow())return;const form=document.getElementById('goal-form');if(!form.reportValidity())return;const goal={id:form.dataset.goalId||crypto.randomUUID(),title:document.getElementById('g-title').value.trim(),target:Number(document.getElementById('g-target').value),basis:document.getElementById('g-basis').value,current:Number(document.getElementById('g-current').value),monthly:Number(document.getElementById('g-monthly').value),due:document.getElementById('g-due').value||null};await saveExtra(n=>{n.insights.goals=n.insights.goals.filter(x=>x.id!==goal.id);n.insights.goals.push(goal);});closeSheet();break;}
 case 'goal-delete':{const id=el.dataset.id;openSheet('Eliminar objetivo','<p class="note">Se elimina solo la meta, no tus saldos ni el historial.</p><button type="button" class="btn danger wide" data-xact="goal-delete-confirm" data-id="'+esc(id)+'">Confirmar eliminaci&oacute;n</button>');break;}
 case 'goal-delete-confirm':await saveExtra(n=>{n.insights.goals=n.insights.goals.filter(x=>x.id!==el.dataset.id);});closeSheet();break;
 case 'close-confirm':closeDialog();break;
 case 'close-save':{const marked=[...document.querySelectorAll('[data-close-date]')].filter(e=>e.checked&&!e.disabled).map(e=>e.dataset.closeDate);const shown=[...document.querySelectorAll('[data-close-date]')].map(e=>e.dataset.closeDate);await saveExtra(n=>{shown.forEach(d=>delete n.insights.closes[d]);marked.forEach(d=>n.insights.closes[d]=A.stamp(n.snapshots[d]));});closeSheet();break;}
 case 'flow-edit':flowDialog(el.dataset.id);break;
 case 'flow-save':{if(!checkShow())return;const form=document.getElementById('flow-form');if(!form.reportValidity())return;const date=form.dataset.date,r=A.portfolioMonths(payload).find(x=>x.to===date);const items=A.parseFlows(document.getElementById('flow-items').value,r.from,r.to);await saveExtra(n=>{n.insights.flows[date]={startDate:r.from,startStamp:A.stamp(n.snapshots[r.from]),endStamp:A.stamp(n.snapshots[r.to]),items};});closeSheet();break;}
 case 'benchmark-import':benchmarkDialog();break;
 case 'benchmark-template':ctx.download('quijo-benchmark-plantilla.csv','mes;rentabilidad_pct;libre_riesgo_pct;defensivo_pct\n','text/csv;charset=utf-8');break;
 case 'benchmark-preview':{const f=document.getElementById('benchmark-form');if(!f.reportValidity())return;pendingBenchmark=A.parseBenchmark(document.getElementById('bm-text').value,{id:crypto.randomUUID(),name:document.getElementById('bm-name').value,source:document.getElementById('bm-source').value,currency:'EUR',reinvested:document.getElementById('bm-confirm').checked,riskFreeSource:document.getElementById('bm-rf-source').value,defensiveSource:document.getElementById('bm-def-source').value});const b=pendingBenchmark;openSheet('Revisar serie de referencia','<div class="stack-sm"><h2>'+esc(b.name)+'</h2><p class="provenance">'+esc(b.source)+'</p>'+badge(b.rows[0].period+' &rarr; '+b.rows.at(-1).period+' &middot; '+b.rows.length+' meses')+'<div class="table-scroll"><table class="summary-table"><thead><tr><th>Mes</th><th>Referencia</th><th>Sin riesgo</th><th>Defensivo</th></tr></thead><tbody>'+b.rows.slice(-8).map(r=>'<tr><td>'+r.period+'</td><td>'+percent(r.returnPct)+'</td><td>'+percent(r.riskFreePct)+'</td><td>'+percent(r.defensivePct)+'</td></tr>').join('')+'</tbody></table></div><p class="note">Se valida el formato, no la exactitud del proveedor. Esta app no atribuye los datos a MSCI ni a iShares por el nombre que escribas.</p>'+btn('benchmark-save','Confirmar serie','check','primary wide')+'</div>');break;}
 case 'benchmark-save':if(!pendingBenchmark)return;await saveExtra(n=>{if(n.insights.benchmarks.length>=8)throw Error('Elimina una referencia antes de anadir otra (maximo 8).');n.insights.benchmarks.push(pendingBenchmark);benchmarkChoice=pendingBenchmark.id;});pendingBenchmark=null;closeSheet();break;
 case 'bm-mode-index':benchmarkMode='index';ctx.render();break;
 case 'bm-mode-mix':benchmarkMode='mix';ctx.render();break;
 case 'benchmark-delete':openSheet('Eliminar referencia','<p class="note">No se borrar&aacute;n las fotos ni tus flujos conciliados.</p>'+btn('benchmark-delete-confirm','Confirmar eliminaci&oacute;n','close','danger wide'));break;
 case 'benchmark-delete-confirm':{const b=selectedBenchmark();await saveExtra(n=>{n.insights.benchmarks=n.insights.benchmarks.filter(x=>x.id!==b.id);});benchmarkChoice=null;closeSheet();break;}
 case 'benchmark-export':{const b=selectedBenchmark(),c=A.compare(payload,b,benchmarkMode,data.date);if(!c?.rows.length)return;const header='mes;cartera_dietz_pct;referencia_pct;cartera_base_100;referencia_base_100';ctx.download('quijo-comparacion-'+c.to+'.csv',header+'\n'+c.rows.map(r=>[r.period,r.returnPct,r.benchmarkPct,r.portfolioIndex,r.benchmarkIndex].join(';')).join('\n'),'text/csv;charset=utf-8');break;}
 }}
 document.addEventListener('click',e=>{const el=e.target.closest('[data-xact]');if(!el||el.disabled)return;el.disabled=true;Promise.resolve(handle(el.dataset.xact,el)).catch(ctx.errorSheet).finally(()=>{if(el.isConnected)el.disabled=false;});});
 document.addEventListener('change',async e=>{if(e.target.id==='changes-from'){fromChoice=e.target.value;ctx.render();}if(e.target.id==='changes-to'){toChoice=e.target.value;fromChoice=null;ctx.render();}if(e.target.id==='benchmark-select'){benchmarkChoice=e.target.value;ctx.render();}if(e.target.id==='benchmark-file'){const f=e.target.files[0];if(!f)return;if(f.size>500000){toast('CSV demasiado grande (maximo 500 KB).');return;}try{document.getElementById('bm-text').value=await f.text();}catch(err){ctx.errorSheet(err);}}});
 return {homeExtra,portfolioExtra,savingExtra,stockExtra,changesView,goalsView,benchmarkView,reset:()=>{pendingBenchmark=null;fromChoice=null;toChoice=null;benchmarkChoice=null;}};
};
})(window);
