/* Pure model functions. EUR at the imported date; no live quotes. */
(function(global){
'use strict';
const finite=Number.isFinite,sum=xs=>xs.reduce((a,v)=>a+(finite(v)?v:0),0),pct=(n,d)=>d?n/d*100:0;
const blocks=[['equity','RV fondos + PP'],['stocks','Acciones'],['defensive','RF y defensivos'],['cash','Liquidez'],['bitcoin','Bitcoin'],['gold','Oro'],['other','Por clasificar']];
const groups={world:'World - Vanguard + Fidelity',pension:'PP MyInvestor Indexado Global',em:'Robeco Emerging Markets',small:'Vanguard Global Small-Cap',value:'Magallanes European Equity P'};
const dca=[{key:'world',name:'Vanguard Global',pct:68.33333333333333},{key:'em',name:'Robeco Emerging Markets',pct:10},{key:'small',name:'Vanguard Global Small-Cap',pct:10},{key:'pension',name:'PP MyInvestor Global',pct:8.333333333333334},{key:'child-world',name:'Fidelity MSCI World',pct:3.3333333333333335}];
function totals(d){const invested=sum(d.positions.map(p=>p.value)),cash=sum(d.accounts.map(p=>p.value)),restricted=sum(d.accounts.filter(a=>a.restricted).map(a=>a.value)),other=sum(d.realAssets.map(a=>a.value)),debt=sum(d.debts.map(a=>a.value));return {invested,cash,available:cash-restricted,restricted,financial:invested+cash,other,debt,net:invested+cash+other-debt};}
function allocation(d){const t=totals(d);return blocks.map(([key,name])=>{const value=key==='cash'?t.cash:sum(d.positions.filter(p=>p.block===key).map(p=>p.value));return {key,name,value,pct:pct(value,t.financial),color:'var(--'+key+')'};}).filter(b=>b.value!==0);}
function contents(d,block){if(block==='cash')return [{id:'cash',name:'Cuentas y efectivo',value:totals(d).cash,pct:100,items:d.accounts}];const positions=d.positions.filter(p=>p.block===block),total=sum(positions.map(p=>p.value)),result=new Map();for(const p of positions){const id=block==='equity'?p.group:p.id;if(!result.has(id))result.set(id,{id,name:groups[id]||p.displayName||p.name,value:0,items:[]});const g=result.get(id);g.value+=p.value;g.items.push(p);}return [...result.values()].map(g=>({...g,pct:pct(g.value,total)})).sort((a,b)=>b.value-a.value);}
function historical(d,field){return d.history.map(h=>{let value=null;if(field==='investment')value=h.investment;else if(field==='cash')value=h.cash;else if(field==='financial'&&finite(h.cash)&&finite(h.investment))value=h.investment+h.cash;else if(field==='net'&&finite(h.cash)&&finite(h.investment)&&finite(h.otherAssets))value=h.investment+h.cash+h.otherAssets-(h.debt||0);return {period:h.period,value,carriedForward:h.carriedForward};}).filter(p=>finite(p.value));}
function returns(d,year){let cumulative=1;const out=[];for(let i=1;i<d.history.length;i++){const h=d.history[i],prev=d.history[i-1];if(!h.period.startsWith(year))continue;const adjacent=(new Date(h.period+'-01')-new Date(prev.period+'-01'))/86400000<33;if(!adjacent||!finite(h.contribution)||!(prev.investment>0))continue;const r=(h.investment-prev.investment-h.contribution)/prev.investment;if(!finite(r)||r<=-1)continue;cumulative*=1+r;out.push({period:h.period,value:r*100,cumulative:(cumulative-1)*100,flow:h.contribution,start:prev.investment,end:h.investment});}return out;}
function savingMonth(m,ordinary=false){const income=m.income-(ordinary?m.extraIncome:0),expenses=m.expenses-(ordinary?m.extraExpenses:0);return {...m,income,expenses,net:income-expenses,rate:income?100*(income-expenses)/income:null};}
function savings(d,year,ordinary=false){const months=d.savings.filter(m=>m.period.startsWith(year)).map(m=>savingMonth(m,ordinary));const income=sum(months.map(m=>m.income)),expenses=sum(months.map(m=>m.expenses));return {months,income,expenses,net:income-expenses,rate:income?100*(income-expenses)/income:null,count:months.length};}
function stockTotals(d){const ss=d.positions.filter(p=>p.kind==='stock'),value=sum(ss.map(s=>s.value)),cost=sum(ss.map(s=>s.cost)),dividends=sum(ss.map(s=>s.dividends)),gain=value-cost+dividends;return {value,cost,dividends,gain,rate:cost?100*gain/cost:null,count:ss.length};}
function publicExport(d){return {schema:'quijocartera-publica',version:1,date:d.date,currency:'EUR',basis:'Porcentajes sobre el patrimonio financiero al cierre. No se incluyen importes ni cantidades.',blocks:allocation(d).map(b=>({key:b.key,name:b.name,pct:Number(b.pct.toFixed(4)),products:contents(d,b.key).map(g=>({name:g.name,pctWithinBlock:Number(g.pct.toFixed(4)),pctTotal:Number((g.pct*b.pct/100).toFixed(4)),identifiers:b.key==='cash'?[]:g.items.map(p=>p.isin||p.ticker||(p.kind==='pension'?'Plan de pensiones':null)).filter(Boolean)}))})),dca:dca.map(p=>({name:p.name,pct:Number(p.pct.toFixed(4))})),note:'Los porcentajes visibles pueden no sumar exactamente 100 por redondeo. Gamma es mixto; AXA es monetario dentro de RF y defensivos. No es una recomendacion de inversion.'};}
function fire(d,s){const t=totals(d),child=sum(d.positions.filter(p=>p.earmarked).map(p=>p.value)),pp=s.includePensions?0:sum(d.positions.filter(p=>p.kind==='pension').map(p=>p.value));const base=Math.max(0,t.financial-child-pp-(s.reserve||0)),target=s.spending/(s.withdrawal/100);const scenarios=[s.realReturn-2,s.realReturn,s.realReturn+2].map(r=>{let value=base,years=value>=target?0:null;const points=[value];for(let n=1;n<=60;n++){value=value*(1+r/100)+s.annualNewSavings;points.push(value);if(years===null&&value>=target)years=n;}return {r,years,age:years===null?null:s.age+years,points};});return {base,target,child,excludedPensions:pp,progress:pct(base,target),scenarios};}
global.QFModel={totals,allocation,contents,historical,returns,savings,savingMonth,stockTotals,publicExport,fire,dca,sum,pct};
})(window);
